name: Publish Java Package to GitHub Package

on:
  push:
    tags: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11.0.9
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.9
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Notify build finish
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: Build結果
        fields: ref,job
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11.0.9
      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify build finish
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Publish結果
          fields: ref,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
        